### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by sfchen** [OpenGene/GeneMisc.jl#1]
==============================[ ERROR: GeneMisc ]===============================

LoadError: UndefVarError: build_index not defined
while loading /Users/shifu/.julia/v0.5/GeneMisc/deps/build.jl, in expression starting on line 14
#

**Comment by zhmz90** [comment]
Sorry, this package is not ready to use now.

**Comment by sfchen** [comment]
If so, please state this in the first line of README.md to avoid misunderstanding:)

**Comment by zhmz90** [comment]
Thanks for your advice. it is added now.
